apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: observabilidad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:23.3
        ports:
        - containerPort: 8123
          name: http
        - containerPort: 9000
          name: tcp
        volumeMounts:
        - name: clickhouse-storage
          mountPath: /var/lib/clickhouse
      volumes:
      - name: clickhouse-storage
        persistentVolumeClaim:
          claimName: clickhouse-pvc
