apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: observabilidad
  labels:
    app: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      initContainers:
        - name: copy-users
          image: busybox
          command: ["sh", "-c", "cp /config/* /users/"]
          volumeMounts:
            - name: user-config
              mountPath: /config
            - name: clickhouse-users
              mountPath: /users

      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8123
            - containerPort: 9000
          env:
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-secret
                  key: password

          volumeMounts:
            - name: clickhouse-storage
              mountPath: /var/lib/clickhouse
            - name: clickhouse-users
              mountPath: /etc/clickhouse-server/users.d

          readinessProbe:
            httpGet:
              path: /ping
              port: 8123
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"

      volumes:
        - name: clickhouse-storage
          persistentVolumeClaim:
            claimName: clickhouse-pvc
        - name: user-config
          configMap:
            name: clickhouse-user-config
        - name: clickhouse-users
          emptyDir: {}
