apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
  namespace: observabilidad
type: Opaque
stringData:
  # usar stringData para que no tengas que codificar en base64 aquí
  password: "cambiar-por-tu-password-seguro"
