apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-user-config
  namespace: observabilidad
data:
  default-user.xml: |
    <clickhouse>
      <users>
        <default>
          <password>${CLICKHOUSE_PASSWORD}</password>
          <networks>
            <ip>::/0</ip>
          </networks>
          <profile>default</profile>
          <quota>default</quota>
        </default>
      </users>
    </clickhouse>
