apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observabilidad
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      debug: {}
      zipkin:
        endpoint: "http://zipkin:9411/api/v2/spans"
      otlphttp/victoriametrics:
        compression: gzip
        encoding: proto
        metrics_endpoint: "http://victoriametrics:8428/opentelemetry/v1/metrics"
        logs_endpoint: "http://victoriametrics:9428/insert/opentelemetry/v1/logs"
        tls:
          insecure: true
      clickhouse:
        endpoint: "tcp://clickhouse:9000"
        username: "default"
        password: "${CLICKHOUSE_PASSWORD}"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [zipkin, clickhouse, debug]
        metrics:
          receivers: [otlp]
          exporters: [otlphttp/victoriametrics, debug]
        logs:
          receivers: [otlp]
          exporters: [clickhouse, otlphttp/victoriametrics, debug]
