apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observabilidad
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:55681"

    processors:
      batch:
        timeout: 5s
        send_batch_size: 5000

    exporters:
      debug: {}
      zipkin:
        endpoint: "http://zipkin:9411/api/v2/spans"
      prometheusremotewrite/victoriametrics:
        endpoint: "http://victoriametrics:8428/api/v1/write"
        headers:
          Authorization: "Basic YWRtaW46Y2FtcGJhci1wb3ItcGFzc3dvcmQ="
      clickhouse:
        endpoint: "tcp://clickhouse:9000?dial_timeout=10s&compress=lz4&async_insert=1"
        database: "default"
        username: "default"
        password: "${CLICKHOUSE_PASSWORD}"
        logs_table_name: "otel_logs"
        traces_table_name: "otel_traces"
        create_schema: true
        timeout: 5s
        sending_queue:
          queue_size: 1000
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhouse, zipkin, debug]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheusremotewrite/victoriametrics, debug]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhouse, debug]
