apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observabilidad
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    exporters:
      debug:
        loglevel: info
      zipkin:
        endpoint: "http://zipkin:9411/api/v2/spans"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [debug, zipkin]
