apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: observabilidad
spec:
  selector:
    app: otel-collector
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 55681
      targetPort: 55681
