apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: observabilidad
spec:
  selector:
    app: victoriametrics
  type: ClusterIP
  ports:
    - name: http
      port: 8428
      targetPort: 8428
