apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: observabilidad:apps/StatefulSet:observabilidad/victoriametrics
  labels:
    app: victoriametrics
  name: victoriametrics
  namespace: observabilidad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoriametrics
  serviceName: victoriametrics
  template:
    metadata:
      labels:
        app: victoriametrics
    spec:
      containers:
        - args:
            - "-retentionPeriod=3"
            - "-storageDataPath=/victoria-metrics-data"
            - "-httpAuth.username=admin"
            - "-httpAuth.password=campbar-por-password"
          image: victoriametrics/victoria-metrics:latest
          imagePullPolicy: IfNotPresent
          name: victoriametrics
          ports:
            - containerPort: 8428
              name: http
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /victoria-metrics-data
              name: vm-storage
  volumeClaimTemplates:
    - metadata:
        name: vm-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: local-path
