apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zipkin-pvc
  namespace: observabilidad
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
