apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: observabilidad
spec:
  selector:
    app: zipkin
  type: ClusterIP
  ports:
    - port: 9411
      targetPort: 9411
      name: http
