apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-pvc
  namespace: observabilidad
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
