apiVersion: v1
kind: Service
metadata:
  name: victoria-metrics
  namespace: observabilidad
spec:
  type: ClusterIP
  selector:
    app: victoria-metrics
  ports:
  - port: 8428
    targetPort: 8428
    name: http
