apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: observabilidad
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: ClickHouse
        type: vertamedia-clickhouse-datasource
        access: proxy
        url: http://clickhouse.observabilidad.svc.cluster.local:8123
        editable: true

      - name: VictoriaMetrics
        type: prometheus
        access: proxy
        url: http://victoriametrics.observabilidad.svc.cluster.local:8428
        editable: true

      - name: Zipkin
        type: zipkin
        access: proxy
        url: http://zipkin.observabilidad.svc.cluster.local:9411
        editable: true
